version: "3.7"
services:
  event_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
    links:
      - mysql_db:mysql_db_host
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: food_logiq_events
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
      MYSQL_ROOT_PASSWORD: admin@123